name: Daily Cypress Test

on:
  schedule:
    - cron: '0 7 * * *' # Runs every day at 7:00 AM UTC
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you need

      - name: Install dependencies and run cypress
        run: |
           npm install
           npx cypress run
